### ISSUE TITLE
Multiple Feature File Support?

### ISSUE THREAD

**Issue by KamiKazi** [mlev/protractor-cucumber-example#1]
Does this allow you to use multiple feature files (specs) support? Would you be able to provide an example?

**Comment by mlev** [comment]
Yes - any feature file you put within the features directory will be picked up automatically. If you'd like to use a different location then just update the protractor.conf.js. 

e.g. this section specifies the locations for the specs

```
specs: [
    'features/*.feature'
  ]
```
